name: run-project-analyze.yml

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run: uv sync --group dev

      - name: Run Ruff
        run: just lint

      - name: Run MyPy
        run: just static-analysis

      - name: Run Tests
        run: just test
